// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtJrXEeqbD-l3RgUGaqm9fHGrMT0WmXFM',
    appId: '1:594053803512:web:ee2f62a267b15016217a0d',
    messagingSenderId: '594053803512',
    projectId: 'notes-ec22d',
    authDomain: 'notes-ec22d.firebaseapp.com',
    databaseURL: 'https://notes-ec22d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-ec22d.appspot.com',
    measurementId: 'G-DLP4K8NX2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5E28wFkmhman_dwm3RWiUYwj4TEY7g_g',
    appId: '1:594053803512:android:48ff6634627dbddc217a0d',
    messagingSenderId: '594053803512',
    projectId: 'notes-ec22d',
    databaseURL: 'https://notes-ec22d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-ec22d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_GXxIOBZPwbmy36HLr2DREUbxREQgCg',
    appId: '1:594053803512:ios:00f5e05b1026b55f217a0d',
    messagingSenderId: '594053803512',
    projectId: 'notes-ec22d',
    databaseURL: 'https://notes-ec22d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-ec22d.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_GXxIOBZPwbmy36HLr2DREUbxREQgCg',
    appId: '1:594053803512:ios:bf92a81ad187e385217a0d',
    messagingSenderId: '594053803512',
    projectId: 'notes-ec22d',
    databaseURL: 'https://notes-ec22d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notes-ec22d.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
